repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: openebs
    url: https://openebs.github.io/charts
  - name: minio
    url: https://operator.min.io/
  - name: twuni
    url: https://helm.twun.io

 
helmDefaults:
  # wait for k8s resources via --wait. (default false)
  wait: true
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 300
  # forces resource update through delete/recreate if needed (default false)
  force: true
  # limit the maximum number of revisions saved per release. Use 0 for no limit. (default 10)
  historyMax: 10
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "v1.3.0"
    values:
      # Value files passed via --values
      - values/cert-manager.yaml
    hooks:
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - delete
          - namespace
          - cert-manager
  - name: openebs
    namespace: openebs
    chart: openebs/openebs
    version: "v2.8.0"
    hooks:
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - delete
          - namespace
          - openebs
  - name: minio-operator
    namespace: minio-operator
    chart: minio/minio-operator
    values:
      # Value files passed via --values
      - values/minio-operator.yaml
    version: "v4.0.8"
    hooks:
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - delete
          - namespace
          - minio-operator
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: "v1.6.1"
    values:
      # Value files passed via --values
      - values/harbor.yaml
