apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: test
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: containous/whoami 
        name: whoami
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: test
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - secretName: tls-cert
      hosts:
        - whoami.local.dev
  rules:
    - host: whoami.local.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: whoami
              port:
                number: 80
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: whoami-cert
  namespace: test
spec:
  isCA: true
  commonName: whoami-cn
  secretName: tls-cert
  dnsNames:
    - whoami.local.dev
  issuerRef:
    name: mkcert-local
    kind: ClusterIssuer
