apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: "minio-{{ .Values.name }}"
  labels:
    app: "minio-{{ .Values.name }}"
  annotations:
    prometheus.io/path: "/minio/{{ .Values.name }}/prometheus/metrics"
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  image: minio/minio:RELEASE.2021-04-06T23-11-00Z 
  imagePullPolicy: IfNotPresent
  credsSecret:
    name: "minio-creds-secret-{{ .Values.name }}"
  pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: "minio-pvc-{{ .Values.name }}"
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: {{ .Values.storage }}
      resources:
        {{ toYaml .Values.resources | nindent 8 }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
  mountPath: /export
  requestAutoCert: false
  s3:
    bucketDNS: true
  podManagementPolicy: Parallel
  serviceMetadata:
    minioServiceLabels:
      label: "minio-svc-{{ .Values.name }}"
    minioServiceAnnotations:
      v2.min.io: "minio-svc-{{ .Values.name }}"
    consoleServiceLabels:
      label: "console-svc-{{ .Values.name }}"
    consoleServiceAnnotations:
      v2.min.io: "console-svc-{{ .Values.name }}"
  console:
    image: minio/console:v0.6.6
    replicas: 2
    consoleSecret:
      name: "console-secret-{{ .Values.name }}"
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      runAsNonRoot: true
