## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: "minio-creds-secret-{{ .Values.name }}"
type: Opaque
data:
  accesskey: {{ .Values.secrets.accesskey }}
  secretkey: {{ .Values.secrets.secretkey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "minio-console-secret-{{ .Values.name }}"
type: Opaque
data:
  CONSOLE_PBKDF_PASSPHRASE: {{ .Values.secrets.CONSOLE_PBKDF_PASSPHRASE }}
  CONSOLE_PBKDF_SALT: {{ .Values.secrets.CONSOLE_PBKDF_SALT }}
  CONSOLE_ACCESS_KEY: {{ .Values.secrets.CONSOLE_ACCESS_KEY }}
  CONSOLE_SECRET_KEY: {{ .Values.secrets.CONSOLE_SECRET_KEY }}
